name: ChangeVersion

on:
  push:
    branches:
      - release

  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: change version

    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'release'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^9.6.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Change version
        uses: changesets/action@v1
        with:
          commit: 'chore: update versions commit'
          title: 'chore: update versions title'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
